---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-task-storage
spec:
  resources:
    requests:
      storage: 32M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gen-random-text
spec:
  workspaces:
    - name: result-storages
  results:
    - name: text
      # The result is reference, so it will use workspace to store its contents.
      isRef: "yes"
      description: large randomly generated string
  steps:
    - name: add
      image: alpine
      command: ["/bin/sh", "-c"]
      # Generate a very large amount of data(~6MB) to result named text of type reference.
      args:
        - cat /dev/urandom | base64 | head -c 6000000 | tee $(results.text.path);
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: concat-text
spec:
  workspaces:
    - name: result-storages
  params:
    - name: first
      description: the first operand
    - name: second
      description: the second operand
  results:
    - name: concatenated-text
      description: concatenate strings
      isRef: "yes"
  steps:
    - name: concat
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - cat $(params.first) $(params.second) | tee $(results.concatenated-text.path) ;
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: concat-text-pipeline
spec:
  tasks:
    - name: first-task
      taskRef:
        name: gen-random-text
      workspaces:
        - name: result-storages
          workspace: shared-data
    - name: second-task
      runAfter:
        - first-task
      taskRef:
        name: gen-random-text
      workspaces:
        - name: result-storages
          workspace: shared-data
    - name: third-task
      runAfter:
        - second-task
      params:
        - name: first
          value: $(tasks.first-task.results.text)
        - name: second
          value: $(tasks.second-task.results.text)
      taskRef:
        name: concat-text
      workspaces:
        - name: result-storages
          workspace: shared-data
  results:
    - name: sum
      isRef: "yes"
      description: the concat of all texts
      value: $(tasks.third-task.results.concatenated-text)
  workspaces:
    - name: shared-data
  # Specify which workspace should be used for storing results.
  resultWorkspace:
    name: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: concat-text-pipeline-run
spec:
  pipelineRef:
    name: concat-text-pipeline
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-task-storage
